export const currentUser = {
  id: 'usr_me',
  fullName: 'Erşad Başbağ',
  username: 'ersad_basbag',
  location: 'Istanbul, Turkey',
  title: 'Senior Product Designer & Frontend Architect',
  bio: 'Designing calm, editorial digital spaces. Focused on design systems, human-centered UI & modern web technologies. @HorizonTechX',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  coverPhoto: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
  website: 'https://horizontechx.com',
  followersCount: 2420,
  followingCount: 480,
  postsCount: 42,
  isVerified: true,
  pages: [
    {
      id: 'pg_1',
      name: 'Twitter',
      category: 'Social Media Platform',
      badge: 2,
      avatar: 'https://images.unsplash.com/photo-1611605698335-8b1569810432?auto=format&fit=crop&w=100&q=80',
      color: 'bg-sky-500',
    },
    {
      id: 'pg_2',
      name: 'Horizon Labs',
      category: 'Software & AI Research',
      badge: 4,
      avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=100&q=80',
      color: 'bg-indigo-600',
    },
  ],
  projects: [
    {
      id: 'prj_1',
      name: 'Github',
      category: 'Coding Platform',
      badge: 2,
      avatar: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=100&q=80',
      color: 'bg-amber-600',
    },
    {
      id: 'prj_2',
      name: 'Apple',
      category: 'Business Company',
      badge: 2,
      avatar: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=100&q=80',
      color: 'bg-neutral-900',
    },
  ],
};

export const mockUsers = [
  {
    id: 'usr_alan',
    fullName: 'Alan Patterson',
    username: 'alanp',
    role: 'Product Strategy & Design',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    bio: 'Building sustainable digital products. Speaker, writer & advisor.',
    followersCount: 14200,
    followingCount: 650,
    isVerified: true,
    isFollowing: false,
  },
  {
    id: 'usr_vintage',
    fullName: 'VintagePainting',
    username: 'vintagepaint',
    role: 'Oil & Gouache Artist',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    bio: 'Classical fine art recreated for modern collections. Studio in Florence.',
    followersCount: 198000,
    followingCount: 310,
    isVerified: true,
    isFollowing: true,
  },
  {
    id: 'usr_jessica',
    fullName: 'Jessica Oh',
    username: 'jessica_oh',
    role: 'Watercolor paint artist',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    bio: 'Translating emotional stillness into botanical watercolors.',
    followersCount: 2100000,
    followingCount: 10200,
    postsCount: 100,
    isVerified: true,
    isFollowing: false,
  },
  {
    id: 'usr_nolan',
    fullName: 'Nolan Curtis',
    username: 'nolancurtis',
    role: 'Brand Architect & Director',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    bio: 'Typography enthusiast & visual systems lead.',
    followersCount: 8920,
    followingCount: 420,
    isVerified: true,
    isFollowing: true,
  },
  {
    id: 'usr_lala',
    fullName: 'PaintwithLala',
    username: 'paintwithlala',
    role: 'Watercolor and Acrylic Painting',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    bio: 'Step-by-step workshops, art tutorials & daily creative sketches.',
    followersCount: 32000,
    followingCount: 210,
    isVerified: true,
    isFollowing: false,
  },
  {
    id: 'usr_digital',
    fullName: 'Digital Paintings',
    username: 'digitalpaint',
    role: 'Make art with Procreate',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    bio: 'Procreate brushes, lighting workflows, and concept art.',
    followersCount: 54000,
    followingCount: 180,
    isVerified: true,
    isFollowing: false,
  },
  {
    id: 'usr_creativity',
    fullName: 'CreativitySpace',
    username: 'creativityspace',
    role: 'Creativity is never wrong',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=200&q=80',
    bio: 'Daily inspiration for independent makers, designers & writers.',
    followersCount: 91000,
    followingCount: 88,
    isVerified: true,
    isFollowing: false,
  },
  {
    id: 'usr_colorful',
    fullName: 'ColorfulSpace',
    username: 'colorfulspace',
    role: 'Colorful life & curation',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    bio: 'Vibrant palettes and creative explorations.',
    followersCount: 41000,
    followingCount: 290,
    isVerified: true,
    isFollowing: true,
  },
];

export const mockStories = [
  {
    id: 'story_add',
    isAddStory: true,
    user: currentUser,
  },
  {
    id: 'story_1',
    user: {
      fullName: 'ColorfulSpace',
      username: 'colorfulspace',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      isVerified: true,
    },
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
    timestamp: '35m ago',
  },
  {
    id: 'story_2',
    user: {
      fullName: 'VintagePainting',
      username: 'vintagepaint',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
      isVerified: true,
    },
    image: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=600&q=80',
    timestamp: '2h ago',
  },
  {
    id: 'story_3',
    user: {
      fullName: 'PencilArtist',
      username: 'pencilartist',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      isVerified: false,
    },
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
    timestamp: '4h ago',
  },
  {
    id: 'story_4',
    user: {
      fullName: 'Jessica Oh',
      username: 'jessica_oh',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      isVerified: true,
    },
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80',
    timestamp: '6h ago',
  },
  {
    id: 'story_5',
    user: {
      fullName: 'Pierre Rushman',
      username: 'pierrerush',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      isVerified: false,
    },
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    timestamp: '8h ago',
  },
];

export const mockPosts = [
  {
    id: 'post_1',
    author: {
      id: 'usr_alan',
      fullName: 'Alan Patterson',
      username: 'alanp',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
      isVerified: false,
    },
    timestamp: '2 hours ago',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    content: 'Was great meeting up with Anna Ferguson and Dave Bishop at the breakfast talk! 🍕 #breakfast',
    images: [
      'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=80',
    ],
    likesCount: 45,
    isLiked: false,
    commentsCount: 16,
    sharesCount: 7,
    isBookmarked: false,
    comments: [
      {
        id: 'c_1',
        author: {
          fullName: 'Anna Ferguson',
          username: 'annaferg',
          avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
        },
        text: 'The ricotta pancakes were unbelievable! Let us repeat this next Thursday.',
        timestamp: '1 hour ago',
        likesCount: 5,
        isLiked: true,
      },
      {
        id: 'c_2',
        author: {
          fullName: 'Dave Bishop',
          username: 'daveb',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
        },
        text: 'Fantastic session discussing decentralized identity protocols. Always insightful.',
        timestamp: '45m ago',
        likesCount: 3,
        isLiked: false,
      },
    ],
  },
  {
    id: 'post_2',
    author: {
      id: 'usr_vintage',
      fullName: 'VintagePainting',
      username: 'vintagepaint',
      avatar: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=200&q=80',
      isVerified: true,
    },
    timestamp: '13 hours ago',
    createdAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    content: 'Hi guys👋 This is my latest paint. The title is "Secret House in the Forest". #art #painting #vintagePainting',
    images: [
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
    ],
    likesCount: 100,
    isLiked: true,
    commentsCount: 30,
    sharesCount: 54,
    isBookmarked: true,
    comments: [
      {
        id: 'c_3',
        author: {
          fullName: 'Jessica Oh',
          username: 'jessica_oh',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
        },
        text: 'The light composition through the trees is masterfully captured! What medium did you use for the highlights?',
        timestamp: '10 hours ago',
        likesCount: 12,
        isLiked: true,
      },
    ],
  },
  {
    id: 'post_3',
    author: {
      id: 'usr_jessica',
      fullName: 'Jessica Oh',
      username: 'jessica_oh',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      isVerified: true,
    },
    timestamp: '1 day ago',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    content: 'Studio morning: experimenting with high-pigment ultramarine and cold-press cotton grain. Sometimes simplicity in layers creates the most depth. #watercolor #botanical #minimalart',
    images: [
      'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80',
    ],
    likesCount: 342,
    isLiked: false,
    commentsCount: 48,
    sharesCount: 39,
    isBookmarked: false,
    comments: [],
  },
  {
    id: 'post_4',
    author: {
      id: 'usr_nolan',
      fullName: 'Nolan Curtis',
      username: 'nolancurtis',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      isVerified: true,
    },
    timestamp: '2 days ago',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    content: 'Good interfaces feel almost invisible. When the spacing rhythm is exact, typography has clear hierarchy, and contrast is calibrated, users focus entirely on the ideas. Clean, calm, intentional design. 📐✨ #designsystems #productdesign',
    images: [],
    likesCount: 89,
    isLiked: true,
    commentsCount: 14,
    sharesCount: 22,
    isBookmarked: true,
    comments: [],
  },
];

export const mockTrendingTopics = [
  { tag: '#art', postsCount: '400 posts', category: 'Fine Arts' },
  { tag: '#illustration', postsCount: '370 posts', category: 'Creative' },
  { tag: '#PaintingTimelapse', postsCount: '352 posts', category: 'Tutorials' },
  { tag: '#landscapepaintings', postsCount: '157 posts', category: 'Trending' },
  { tag: '#acrylicPaintings', postsCount: '130 posts', category: 'Traditional' },
  { tag: '#HowtoPaint', postsCount: '112 posts', category: 'Education' },
  { tag: '#InspiringArt', postsCount: '78 posts', category: 'Community' },
  { tag: '#PaperFlower', postsCount: '50 posts', category: 'Crafts' },
  { tag: '#DesignSystems', postsCount: '980 posts', category: 'Technology' },
  { tag: '#ConnectSphere', postsCount: '620 posts', category: 'Platform' },
];

export const mockNotifications = [
  {
    id: 'notif_1',
    type: 'like',
    user: mockUsers[0],
    text: 'liked your post "Designing calm, editorial digital spaces"',
    timestamp: '10m ago',
    read: false,
  },
  {
    id: 'notif_2',
    type: 'comment',
    user: mockUsers[2],
    text: 'commented: "The light composition through the trees is masterfully captured!"',
    timestamp: '1h ago',
    read: false,
  },
  {
    id: 'notif_3',
    type: 'follow',
    user: mockUsers[1],
    text: 'started following you',
    timestamp: '3h ago',
    read: true,
  },
  {
    id: 'notif_4',
    type: 'mention',
    user: mockUsers[3],
    text: 'mentioned you in a post: "Working with @ersad_basbag on the new design tokens"',
    timestamp: '1d ago',
    read: true,
  },
  {
    id: 'notif_5',
    type: 'system',
    user: {
      fullName: 'ConnectSphere Team',
      username: 'connectsphere',
      avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=100&q=80',
    },
    text: 'Your profile is now verified with the ConnectSphere Creator Badge.',
    timestamp: '2d ago',
    read: true,
  },
];

export const mockConversations = [
  {
    id: 'conv_1',
    user: mockUsers[3], // Nolan Curtis
    unreadCount: 2,
    lastMessage: 'Are we still syncing at 3 PM about the typography tokens?',
    lastTimestamp: '12m ago',
    messages: [
      { id: 'm1', senderId: 'usr_nolan', text: 'Hey Erşad! Reviewed the updated design system components.', time: '10:15 AM' },
      { id: 'm2', senderId: 'usr_me', text: 'Awesome! Did the spacing tokens feel right in the feed view?', time: '10:18 AM' },
      { id: 'm3', senderId: 'usr_nolan', text: 'Yes, the 8px rhythm feels much more grounded and calm.', time: '10:20 AM' },
      { id: 'm4', senderId: 'usr_nolan', text: 'Are we still syncing at 3 PM about the typography tokens?', time: '10:22 AM' },
    ],
  },
  {
    id: 'conv_2',
    user: mockUsers[2], // Jessica Oh
    unreadCount: 0,
    lastMessage: 'Thank you! Excited to collaborate on the upcoming exhibition.',
    lastTimestamp: '2h ago',
    messages: [
      { id: 'm5', senderId: 'usr_me', text: 'Hi Jessica, loved your latest botanical series!', time: 'Yesterday' },
      { id: 'm6', senderId: 'usr_jessica', text: 'Thank you! Excited to collaborate on the upcoming exhibition.', time: '2h ago' },
    ],
  },
  {
    id: 'conv_3',
    user: mockUsers[0], // Alan Patterson
    unreadCount: 0,
    lastMessage: 'Let us touch base tomorrow morning.',
    lastTimestamp: '1d ago',
    messages: [
      { id: 'm7', senderId: 'usr_alan', text: 'Let us touch base tomorrow morning.', time: 'Yesterday' },
    ],
  },
];

export const mockCommunities = [
  {
    id: 'comm_1',
    name: 'Indonesian Artist',
    membersCount: '24.5k',
    avatar: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=120&q=80',
    hasUnread: true,
    isJoined: true,
    category: 'Art & Culture',
    description: 'Community for Indonesian traditional and contemporary visual artists.',
  },
  {
    id: 'comm_2',
    name: 'Watercolor Artist Collective',
    membersCount: '68.1k',
    avatar: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=120&q=80',
    hasUnread: false,
    isJoined: true,
    category: 'Traditional Art',
    description: 'Global watercolorists sharing wet-on-wet techniques and pigment studies.',
  },
  {
    id: 'comm_3',
    name: 'Digital Illustrator Community',
    membersCount: '112k',
    avatar: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=120&q=80',
    hasUnread: true,
    isJoined: true,
    category: 'Digital Art',
    description: 'Concept art, 2D illustration, Procreate & Photoshop tips.',
  },
  {
    id: 'comm_4',
    name: 'Art Market Worldwide',
    membersCount: '89.4k',
    avatar: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=120&q=80',
    hasUnread: false,
    isJoined: false,
    category: 'Marketplace',
    description: 'Connecting collectors, gallery curators, and independent artists worldwide.',
  },
];
